services:
  nginx:
    image: nginx:stable-alpine
    container_name: npepub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  backend:
    image: ghcr.io/woody-rn/npepub-backend:latest
    container_name: npepub-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/npepub
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  frontend:
    image: ghcr.io/woody-rn/npepub-frontend:latest
    container_name: npepub-frontend
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: npepub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: npepub
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: npepub_pg_data